[package]
name = "glassbeadgame"
version = "0.1.0"
edition = "2018"
authors = ["test@test.com"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "glassbeadgame"

[dependencies]
hdk = {version = "0.0.123", features = ["encoding"]}
serde = "1.0"
derive_more = "0"
chrono = "0.4"
