[package]
name = "glassbeadgame"
version = "0.1.0"
edition = "2021"
authors = ["eric@harris-braun.com"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "glassbeadgame"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
holochain_serialized_bytes = { workspace = true }

glassbeadgame_integrity = { workspace = true }
